[package]
name = "lnpl"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = "1.1.0"

[lib]
name = "lnpl"
doctest = false
bench = false

[[bin]]
name = "main"
test = false
bench = false

[[bin]]
name = "perfhash"
test = false
bench = false


